# -*- coding: utf-8 -*-
"""Face Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3T1xMNcg1X6IvctG6jZg1B_0I3znmGF
"""

!pip install face_recognition

!mkdir known
!wget https://www.biography.com/.image/t_share/MTY2MzU3Nzk2OTM2MjMwNTkx/elon_musk_royal_society.jpg -O known/elon.jpg
!wget https://pbs.twimg.com/profile_images/988775660163252226/XpgonN0X_400x400.jpg -O known/bill.jpg
!wget https://www.biography.com/.image/t_share/MTE4MDAzNDEwNzg5ODI4MTEw/barack-obama-12782369-1-402.jpg -O known/obama.jpg

!mkdir unknown
!wget https://i.insider.com/5ddfa893fd9db26b8a4a2df7 -O unknown/1.jpg
!wget https://cdn-images-1.medium.com/max/1200/1*aEoYLgy4z1lT1kW7dqWzBg.jpeg -O unknown/2.jpg
!wget https://media2.s-nbcnews.com/j/newscms/2017_46/2224911/171113-bill-gates-se-247p_043bd413c63b2a97abf11bfad747538d.fit-760w.jpg -O unknown/3.jpg
!wget https://specials-images.forbesimg.com/imageserve/1184274010/960x0.jpg -O unknown/4.jpg

import face_recognition
import cv2
import os
from google.colab.patches import cv2_imshow

def read_img(path):
    img = cv2.imread(path)
    (h, w) = img.shape[:2]
    width = 500
    ratio = width / float(w)
    height = int(h * ratio)
    return cv2.resize(img, (width, height))


known_encodings = []
known_names = []
known_dir = 'known'

for file in os.listdir(known_dir):
    img = read_img(known_dir + '/' + file)
    img_enc = face_recognition.face_encodings(img)[0]
    known_encodings.append(img_enc)
    known_names.append(file.split('.')[0])

unknown_dir = 'unknown'
for file in os.listdir(unknown_dir):
    print("Processing", file)
    img = read_img(unknown_dir + '/' + file)
    img_enc = face_recognition.face_encodings(img)[0]

    results = face_recognition.compare_faces(known_encodings, img_enc)
    # print(face_recognition.face_distance(known_encodings, img_enc))

    for i in range(len(results)):
        if results[i]:
            name = known_names[i]
            (top, right, bottom, left) = face_recognition.face_locations(img)[0]
            cv2.rectangle(img, (left, top), (right, bottom), (0, 0, 255), 2)
            cv2.putText(img, name, (left+2, bottom+20), cv2.FONT_HERSHEY_PLAIN, 1, (255, 255, 255), 1)
            cv2_imshow(img)


    # print(results)

import cv2

import face_recognition

# step 1 :
# path = '/content/drive/MyDrive/Machine Learning/Python/2024/pic//'
imgElon = face_recognition.load_image_file("elon musk.jpg")
imgElon =cv2.cvtColor(imgElon,cv2.COLOR_BGR2RGB)
imgCheck = face_recognition.load_image_file("elon check.jpg")
imgCheck =cv2.cvtColor(imgCheck,cv2.COLOR_BGR2RGB)

# Xác đinh vị trí khuôn mặt cần nhận dạng
faceloc = face_recognition.face_locations(imgElon)[0]
print(faceloc) #(y1,x2,y2,x1)

encodeElon = face_recognition.face_encodings(imgElon)[0] # mã hóa ảnh
cv2.rectangle(imgElon,(faceloc[3],faceloc[0]),(faceloc[1],faceloc[2]),(255,0,255),2)

faceCheck = face_recognition.face_locations(imgCheck)[0]
encodeCheck = face_recognition.face_encodings(imgCheck)[0] # mã hóa ảnh
cv2.rectangle(imgCheck,(faceCheck[3],faceCheck[0]),(faceCheck[1],faceCheck[2]),(255,0,255),2)

# nó sẽ so sánh hình ảnh mã hóa với các điểm trên khuôn mặt xem có khớp o
results = face_recognition.compare_faces([encodeElon],encodeCheck)
print(results) # Kết quả True

# tuy nhiên khi có nhiều hình ảnh thì chúng ta cần phải biết
# khoảng cách (sai số ) giữa các bức ảnh là bao nhiêu?
faceDis = face_recognition.face_distance([encodeElon],encodeCheck)
print(results,faceDis)
#
cv2.putText(imgCheck,f"{results}{(round(faceDis[0],2))}",(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)

cv2_imshow(imgElon)  # view thử ảnh để kiểm tra
cv2_imshow(imgCheck) # view thử ảnh
cv2.waitKey()
cv2.destroyAllWindows()  # thoát tất cả các cửa sổ